// 设置token的临时脚本
const token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6ImFtcyIsImNsaWVudFR5cGUiOiJhZG1pbiIsInVzZXJfbmFtZSI6InBwcCIsInNjb3BlIjpbImFsbCJdLCJleHAiOjIxMDk4NjA5NjQsInVzZXJJZCI6MjgsImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6IjBlYjYxZTJiLTI0N2UtNDQ1Zi1hZjAxLTgzN2NmZGIxYWZlNiIsImNsaWVudF9pZCI6ImFtcyIsInVzZXJuYW1lIjoicHBwIn0.VBhBF19uW2EOIQdGpj8oOduHn1JPGqvS40VgxXnG_1ZV9zyFVsa6DkMpP-NUHjaFWHieraAomsxRTHM8EzRfZPpUiewFF4e-lw7fbJL2e27DPqSv0VomXFiRJbQXJuncewXchgt-3PYw94wcLDGvS4HxojaKoJ51oh-XJPWYKIdjw9o_TFTEt9p2pV552_g4I4vK_kKYIr0CDoQP7hwQKQj3pYO5MHAOL44tdbh9abt97RHpc8wQZozLqJpM4EP8cc4pxU2dkA7__LYWktpRHB01gs_cKBxp-e_4Fd9gvdVefw9JpGahyc3ZF9KRwHYLy8tNof-QVF_-NpnNA7xOMQ";

localStorage.setItem('access_token', token);
localStorage.setItem('token', token);

console.log('Token已设置:', token);
console.log('验证token:', localStorage.getItem('access_token'));
